# Generated by Django 3.0.2 on 2020-01-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pooja',
            old_name='name',
            new_name='pooja',
        ),
    ]
