# Generated by Django 3.0.2 on 2020-01-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200116_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='pooja',
        ),
    ]
