# Generated by Django 3.0.2 on 2020-01-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200116_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='pooja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Pooja'),
        ),
    ]
